import { useState } from 'react';
import {
  Dna, Loader2, Sparkles, TrendingUp, TrendingDown,
  Clock, Calendar, Zap, Target, BarChart2, Download,
  RefreshCw, AlertTriangle, CheckCircle, Bug
} from 'lucide-react';
import DashboardLayout from '../components/dashboard/DashboardLayout';
import useDebugDNA from '../hooks/useDebugDNA';
import type { CategoryStat } from '../hooks/useDebugDNA';

const SEVERITY_COLORS: Record<string, string> = {
  critical: 'bg-red-500',
  high: 'bg-orange-500',
  medium: 'bg-yellow-500',
  low: 'bg-green-500',
};

const SEVERITY_TEXT: Record<string, string> = {
  critical: 'text-red-600 bg-red-50 border-red-200',
  high: 'text-orange-600 bg-orange-50 border-orange-200',
  medium: 'text-yellow-600 bg-yellow-50 border-yellow-200',
  low: 'text-green-600 bg-green-50 border-green-200',
};

const WEEK_LABELS = ['This week', 'Last week', '2w ago', '3w ago'];

const CategoryBar = ({ stat, color }: { stat: CategoryStat; color: string }) => (
  <div className="space-y-1.5">
    <div className="flex items-center justify-between gap-2">
      <span className="text-sm text-gray-700 dark:text-gray-300 truncate">{stat.category}</span>
      <div className="flex items-center gap-2 flex-shrink-0">
        <span className="text-xs text-gray-400">{stat.total} sessions</span>
        <span className={`text-xs font-bold ${stat.resolutionRate >= 70 ? 'text-green-600' : stat.resolutionRate >= 40 ? 'text-yellow-600' : 'text-red-600'}`}>
          {stat.resolutionRate}%
        </span>
      </div>
    </div>
    <div className="h-2 bg-gray-100 dark:bg-gray-800 rounded-full overflow-hidden">
      <div
        className={`h-full rounded-full transition-all duration-700 ${color}`}
        style={{ width: `${Math.max(stat.resolutionRate, 3)}%` }}
      />
    </div>
  </div>
);

const DebugDNAPage = () => {
  const { result, loading, error, generate } = useDebugDNA();
  const [exported, setExported] = useState(false);

  const handleExport = () => {
    if (!result) return;
    const { stats, narrative } = result;
    const md = `# My Debug DNA — DevTrace AI\n\n## AI Narrative\n\n${narrative}\n\n## Stats\n\n- Total sessions: ${stats.total}\n- Resolution rate: ${stats.resolutionRate}%\n- Open: ${stats.open} · Resolved: ${stats.resolved}\n- Avg resolution time: ${stats.avgResolutionHours}h\n- Busiest day: ${stats.busiestDay}\n- Top fix type: ${stats.topFixType}\n- Avg AI confidence: ${stats.avgConfidence}%\n\n## Category Breakdown\n\n${stats.categoryStats.map(c => `- ${c.category}: ${c.total} sessions, ${c.resolutionRate}% resolved`).join('\n')}\n\n_Generated by DevTrace AI_`;
    const blob = new Blob([md], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'debug-dna.md';
    a.click();
    URL.revokeObjectURL(url);
    setExported(true);
    setTimeout(() => setExported(false), 2000);
  };

  return (
    <DashboardLayout title="Debug DNA">
      <div className="space-y-6">

        {/* Header */}
        <div className="bg-gradient-to-r from-violet-600 to-indigo-600 rounded-2xl p-5 sm:p-7">
          <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
            <div>
              <div className="flex items-center gap-2 mb-2">
                <div className="w-9 h-9 bg-white/20 rounded-xl flex items-center justify-center">
                  <Dna size={18} className="text-white" />
                </div>
                <span className="text-white/80 text-sm font-medium">Powered by Supabase Edge Functions + Groq</span>
              </div>
              <h2 className="text-xl sm:text-2xl font-bold text-white">Your Debug DNA</h2>
              <p className="text-violet-200 text-xs sm:text-sm mt-1 max-w-md">
                A personalized analysis of your debugging patterns, strengths, and blind spots — generated from your session history.
              </p>
            </div>
            <div className="flex items-center gap-2 flex-shrink-0">
              {result && (
                <button
                  onClick={handleExport}
                  className="flex items-center gap-1.5 border border-white/30 hover:border-white/60 text-white px-3 py-2 rounded-xl text-sm font-medium transition"
                >
                  <Download size={14} />
                  {exported ? 'Exported!' : 'Export .md'}
                </button>
              )}
              <button
                onClick={generate}
                disabled={loading}
                className="flex items-center gap-2 bg-white hover:bg-gray-50 text-indigo-600 font-bold px-5 py-2.5 rounded-xl text-sm transition disabled:opacity-60 shadow-lg"
              >
                {loading
                  ? <><Loader2 size={15} className="animate-spin" /> Analyzing...</>
                  : result
                  ? <><RefreshCw size={15} /> Regenerate</>
                  : <><Sparkles size={15} /> Generate My DNA</>
                }
              </button>
            </div>
          </div>
        </div>

        {/* Empty / error states */}
        {!result && !loading && !error && (
          <div className="bg-white dark:bg-gray-900 rounded-2xl border border-gray-100 dark:border-gray-800 p-12 text-center">
            <div className="w-16 h-16 bg-violet-50 dark:bg-violet-950 rounded-2xl flex items-center justify-center mx-auto mb-4">
              <Dna size={28} className="text-violet-400" />
            </div>
            <h3 className="font-bold text-gray-900 dark:text-white mb-2">Your debugging fingerprint awaits</h3>
            <p className="text-gray-400 text-sm max-w-sm mx-auto mb-6">
              Click "Generate My DNA" to analyze your session history and get a personalized breakdown of your debugging patterns.
            </p>
            <button
              onClick={generate}
              className="flex items-center gap-2 bg-indigo-600 hover:bg-indigo-700 text-white font-semibold px-6 py-3 rounded-xl text-sm transition mx-auto"
            >
              <Sparkles size={15} /> Generate My Debug DNA
            </button>
          </div>
        )}

        {loading && (
          <div className="bg-white dark:bg-gray-900 rounded-2xl border border-gray-100 dark:border-gray-800 p-12 text-center">
            <Loader2 size={32} className="animate-spin text-indigo-500 mx-auto mb-4" />
            <p className="font-semibold text-gray-900 dark:text-white">Analyzing your sessions...</p>
            <p className="text-gray-400 text-sm mt-1">Supabase Edge Function is computing your patterns</p>
          </div>
        )}

        {error === 'no_sessions' && (
          <div className="bg-white dark:bg-gray-900 rounded-2xl border border-gray-100 dark:border-gray-800 p-12 text-center">
            <div className="w-14 h-14 bg-yellow-50 dark:bg-yellow-950 rounded-2xl flex items-center justify-center mx-auto mb-4">
              <Bug size={24} className="text-yellow-500" />
            </div>
            <p className="font-semibold text-gray-900 dark:text-white mb-1">No sessions yet</p>
            <p className="text-gray-400 text-sm">Create some debug sessions first — your DNA needs data to analyze.</p>
          </div>
        )}

        {error && error !== 'no_sessions' && (
          <div className="bg-red-50 dark:bg-red-950 rounded-2xl border border-red-200 dark:border-red-900 p-5 flex items-start gap-3">
            <AlertTriangle size={16} className="text-red-500 flex-shrink-0 mt-0.5" />
            <div>
              <p className="text-sm font-semibold text-red-700 dark:text-red-300">Generation failed</p>
              <p className="text-xs text-red-600 dark:text-red-400 mt-0.5">{error}</p>
            </div>
          </div>
        )}

        {result && !loading && (
          <>
            {/* AI Narrative */}
            <div className="bg-white dark:bg-gray-900 rounded-2xl border border-violet-100 dark:border-violet-900 p-5 sm:p-6">
              <div className="flex items-center gap-2 mb-4">
                <div className="w-8 h-8 bg-violet-50 dark:bg-violet-950 rounded-xl flex items-center justify-center">
                  <Sparkles size={15} className="text-violet-600" />
                </div>
                <h3 className="font-bold text-gray-900 dark:text-white">Your Debugging Profile</h3>
                <span className="text-xs bg-violet-50 dark:bg-violet-950 text-violet-600 border border-violet-100 dark:border-violet-900 px-2 py-0.5 rounded-full font-medium ml-auto">
                  AI Generated
                </span>
              </div>
              <div className="space-y-3">
                {result.narrative.split('\n\n').filter(p => p.trim()).map((para, i) => (
                  <p key={i} className="text-sm text-gray-700 dark:text-gray-300 leading-relaxed">{para}</p>
                ))}
              </div>
            </div>

            {/* Key stats row */}
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 sm:gap-4">
              {[
                { label: 'Total Sessions',    value: result.stats.total,                            icon: <Bug size={18} />,      color: 'text-blue-600',   bg: 'bg-blue-50 dark:bg-blue-950',     sub: 'all time' },
                { label: 'Resolution Rate',   value: `${result.stats.resolutionRate}%`,              icon: <Target size={18} />,   color: 'text-green-600',  bg: 'bg-green-50 dark:bg-green-950',   sub: `${result.stats.resolved} resolved` },
                { label: 'Avg Fix Time',      value: result.stats.avgResolutionHours > 0 ? `${result.stats.avgResolutionHours}h` : '—', icon: <Clock size={18} />, color: 'text-orange-600', bg: 'bg-orange-50 dark:bg-orange-950', sub: 'per session' },
                { label: 'AI Confidence',     value: result.stats.avgConfidence > 0 ? `${result.stats.avgConfidence}%` : '—',    icon: <Zap size={18} />,      color: 'text-violet-600', bg: 'bg-violet-50 dark:bg-violet-950', sub: 'avg across sessions' },
              ].map((c, i) => (
                <div key={i} className="bg-white dark:bg-gray-900 rounded-2xl border border-gray-100 dark:border-gray-800 p-4 sm:p-5">
                  <div className={`w-9 h-9 ${c.bg} rounded-xl flex items-center justify-center ${c.color} mb-3`}>{c.icon}</div>
                  <p className="text-xl sm:text-2xl font-bold text-gray-900 dark:text-white">{c.value}</p>
                  <p className="text-xs sm:text-sm text-gray-500 mt-0.5">{c.label}</p>
                  <p className="text-xs text-gray-400">{c.sub}</p>
                </div>
              ))}
            </div>

            {/* Category breakdown + activity */}
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-5">

              {/* Category resolution rates */}
              <div className="bg-white dark:bg-gray-900 rounded-2xl border border-gray-100 dark:border-gray-800 p-5 sm:p-6">
                <h3 className="font-bold text-gray-900 dark:text-white mb-1 flex items-center gap-2">
                  <BarChart2 size={16} className="text-indigo-500" /> Category Breakdown
                </h3>
                <p className="text-xs text-gray-400 mb-5">Resolution rate by error category</p>
                <div className="space-y-4">
                  {result.stats.categoryStats.map((stat, i) => (
                    <CategoryBar
                      key={i}
                      stat={stat}
                      color={stat.resolutionRate >= 70 ? 'bg-green-400' : stat.resolutionRate >= 40 ? 'bg-yellow-400' : 'bg-red-400'}
                    />
                  ))}
                  {result.stats.categoryStats.length === 0 && (
                    <p className="text-sm text-gray-400 text-center py-4">Analyze more sessions to see category patterns</p>
                  )}
                </div>
              </div>

              {/* Strengths + weaknesses */}
              <div className="space-y-4">

                {/* Strengths */}
                {result.stats.bestCategories.length > 0 && (
                  <div className="bg-white dark:bg-gray-900 rounded-2xl border border-green-100 dark:border-green-900 p-5">
                    <h3 className="font-bold text-gray-900 dark:text-white mb-3 flex items-center gap-2">
                      <TrendingUp size={15} className="text-green-500" /> You Excel At
                    </h3>
                    <div className="space-y-2">
                      {result.stats.bestCategories.map((c, i) => (
                        <div key={i} className="flex items-center justify-between p-2.5 bg-green-50 dark:bg-green-950 rounded-xl">
                          <div className="flex items-center gap-2">
                            <CheckCircle size={13} className="text-green-500 flex-shrink-0" />
                            <span className="text-sm text-gray-700 dark:text-gray-300 truncate">{c.category}</span>
                          </div>
                          <span className="text-sm font-bold text-green-600 flex-shrink-0">{c.resolutionRate}%</span>
                        </div>
                      ))}
                    </div>
                  </div>
                )}

                {/* Weaknesses */}
                {result.stats.hardestCategories.length > 0 && (
                  <div className="bg-white dark:bg-gray-900 rounded-2xl border border-red-100 dark:border-red-900 p-5">
                    <h3 className="font-bold text-gray-900 dark:text-white mb-3 flex items-center gap-2">
                      <TrendingDown size={15} className="text-red-500" /> Needs Attention
                    </h3>
                    <div className="space-y-2">
                      {result.stats.hardestCategories.map((c, i) => (
                        <div key={i} className="flex items-center justify-between p-2.5 bg-red-50 dark:bg-red-950 rounded-xl">
                          <div className="flex items-center gap-2">
                            <AlertTriangle size={13} className="text-red-400 flex-shrink-0" />
                            <span className="text-sm text-gray-700 dark:text-gray-300 truncate">{c.category}</span>
                          </div>
                          <span className="text-sm font-bold text-red-600 flex-shrink-0">{c.resolutionRate}%</span>
                        </div>
                      ))}
                    </div>
                  </div>
                )}

                {/* Habits */}
                <div className="bg-white dark:bg-gray-900 rounded-2xl border border-gray-100 dark:border-gray-800 p-5">
                  <h3 className="font-bold text-gray-900 dark:text-white mb-3 flex items-center gap-2">
                    <Calendar size={15} className="text-indigo-500" /> Your Habits
                  </h3>
                  <div className="space-y-2.5">
                    <div className="flex items-center justify-between text-sm">
                      <span className="text-gray-500">Busiest day</span>
                      <span className="font-semibold text-gray-900 dark:text-white">{result.stats.busiestDay}</span>
                    </div>
                    <div className="flex items-center justify-between text-sm">
                      <span className="text-gray-500">Preferred fix type</span>
                      <span className="font-semibold text-gray-900 dark:text-white capitalize">{result.stats.topFixType || '—'}</span>
                    </div>
                    <div className="flex items-center justify-between text-sm">
                      <span className="text-gray-500">Open sessions</span>
                      <span className="font-semibold text-orange-600">{result.stats.open}</span>
                    </div>
                    <div className="flex items-center justify-between text-sm">
                      <span className="text-gray-500">In progress</span>
                      <span className="font-semibold text-blue-600">{result.stats.inProgress}</span>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            {/* Severity breakdown */}
            <div className="bg-white dark:bg-gray-900 rounded-2xl border border-gray-100 dark:border-gray-800 p-5 sm:p-6">
              <h3 className="font-bold text-gray-900 dark:text-white mb-1 flex items-center gap-2">
                <Target size={16} className="text-orange-500" /> Severity Distribution
              </h3>
              <p className="text-xs text-gray-400 mb-5">How you classify your bugs</p>
              <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
                {['critical', 'high', 'medium', 'low'].map(sev => {
                  const count = result.stats.severityMap[sev] ?? 0;
                  const pct = result.stats.total > 0 ? Math.round((count / result.stats.total) * 100) : 0;
                  return (
                    <div key={sev} className={`rounded-xl border p-4 text-center ${SEVERITY_TEXT[sev]}`}>
                      <div className={`w-3 h-3 rounded-full ${SEVERITY_COLORS[sev]} mx-auto mb-2`} />
                      <p className="text-xl font-bold">{count}</p>
                      <p className="text-xs font-semibold capitalize mt-0.5">{sev}</p>
                      <p className="text-xs opacity-70 mt-0.5">{pct}%</p>
                    </div>
                  );
                })}
              </div>
            </div>

            {/* Weekly activity */}
            <div className="bg-white dark:bg-gray-900 rounded-2xl border border-gray-100 dark:border-gray-800 p-5 sm:p-6">
              <h3 className="font-bold text-gray-900 dark:text-white mb-1 flex items-center gap-2">
                <TrendingUp size={16} className="text-blue-500" /> Recent Activity
              </h3>
              <p className="text-xs text-gray-400 mb-5">Sessions logged per week</p>
              <div className="grid grid-cols-4 gap-3">
                {result.stats.weeklyBuckets.map((count, i) => {
                  const maxVal = Math.max(...result.stats.weeklyBuckets, 1);
                  const pct = Math.round((count / maxVal) * 100);
                  return (
                    <div key={i} className="flex flex-col items-center gap-2">
                      <div className="w-full bg-gray-100 dark:bg-gray-800 rounded-xl overflow-hidden h-20 flex items-end">
                        <div
                          className="w-full bg-indigo-400 rounded-xl transition-all duration-700"
                          style={{ height: `${Math.max(pct, 4)}%` }}
                        />
                      </div>
                      <p className="text-xs font-bold text-gray-900 dark:text-white">{count}</p>
                      <p className="text-xs text-gray-400 text-center leading-tight">{WEEK_LABELS[i]}</p>
                    </div>
                  );
                })}
              </div>
            </div>
          </>
        )}

      </div>
    </DashboardLayout>
  );
};

export default DebugDNAPage;